import './globals.css';
import React from 'react';
import { Toaster } from 'sonner';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryProvider from '@/libs/query-provider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const interFont = Inter();
export const metadata: Metadata = {
  title: 'Project Management Tool',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${interFont.className} antialiased`}>
        <Toaster />
        <QueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <TooltipProvider>{children}</TooltipProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
